
import './globals.css'
import { Outfit } from 'next/font/google'
import Header from "@/app/components/Navbar";

const outfit = Outfit({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{fontFamily:outfit}} >

        {children}


        </body>
    </html>
  )
}
